Consolidate scripts (#118)
```
reneetso@Renees-MacBook-Pro aptos-indexer-processors-sdk % sh ./scripts/check_banned_deps.sh 
Checking for banned dependency pq-sys...
error: package ID specification `pq-sys` did not match any packages

help: a package with a similar name exists: `dw-sys`
Checking for banned dependency openssl-sys...
warning: nothing to print.

To find dependencies that require specific target platforms, try to use option `--target all` first, and then narrow your search scope accordingly.
None of the banned dependencies are in use in , great!


reneetso@Renees-MacBook-Pro aptos-indexer-processors-sdk % sh ./scripts/rust_lint.sh 
Starting linting process...

Linting examples directory...
Running lint in examples...
    Checking postgres-basic-events-example v1.0.0 (/Users/reneetso/aptos-indexer-processors-sdk/examples/postgres-basic-events-example)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.61s
Checking examples...
Finished: Cargo.toml for "examples" has been rewritten
Checking postgres-basic-events-example...
Finished: Cargo.toml for "postgres-basic-events-example" has been rewritten

Linting aptos-indexer-processors-sdk directory...
Running lint in aptos-indexer-processors-sdk...
    Checking aptos-moving-average v0.1.0 (/Users/reneetso/aptos-indexer-processors-sdk/aptos-indexer-processors-sdk/moving-average)
    Checking sample v0.1.0 (/Users/reneetso/aptos-indexer-processors-sdk/aptos-indexer-processors-sdk/sample)
    Checking instrumented-channel v0.1.0 (/Users/reneetso/aptos-indexer-processors-sdk/aptos-indexer-processors-sdk/instrumented-channel)
    Checking aptos-indexer-transaction-stream v0.1.0 (/Users/reneetso/aptos-indexer-processors-sdk/aptos-indexer-processors-sdk/transaction-stream)
    Checking aptos-indexer-processor-sdk v0.1.0 (/Users/reneetso/aptos-indexer-processors-sdk/aptos-indexer-processors-sdk/sdk)
    Checking aptos-indexer-testing-framework v0.1.0 (/Users/reneetso/aptos-indexer-processors-sdk/aptos-indexer-processors-sdk/testing-framework)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.82s
Checking aptos-indexer-processors-sdk...
Finished: Cargo.toml for "aptos-indexer-processors-sdk" has been rewritten
Checking instrumented-channel...
Finished: Cargo.toml for "instrumented-channel" has been rewritten
Checking moving-average...
Finished: Cargo.toml for "moving-average" has been rewritten
Checking sample...
Finished: Cargo.toml for "sample" has been rewritten
Checking sdk...
Finished: Cargo.toml for "sdk" has been rewritten
Checking testing-framework...
Finished: Cargo.toml for "testing-framework" has been rewritten
Checking transaction-stream...
Finished: Cargo.toml for "transaction-stream" has been rewritten

Linting completed successfully!
```